//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CommodityMold
    {
        public int CommodityMoldID { get; set; }
        public int MoldID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Remarks { get; set; }
        public decimal Quantity { get; set; }
        public bool IsDefault { get; set; }
        public bool InActive { get; set; }
        public string MoldCode { get; set; }
        public string MoldName { get; set; }
    }
}
