//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CommodityIndex
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public string CodePartA { get; set; }
        public string CodePartB { get; set; }
        public string CodePartC { get; set; }
        public string CodePartD { get; set; }
        public string CodePartE { get; set; }
        public string CodePartF { get; set; }
        public string SalesUnit { get; set; }
        public bool Discontinue { get; set; }
        public bool InActive { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCategoryName1 { get; set; }
        public string CommodityCategoryName2 { get; set; }
        public string OfficialCode { get; set; }
        public Nullable<int> BomID { get; set; }
        public string BomCode { get; set; }
        public string BomName { get; set; }
        public Nullable<decimal> BlockUnit { get; set; }
        public Nullable<decimal> BlockQuantity { get; set; }
        public Nullable<int> MoldID { get; set; }
        public string MoldCode { get; set; }
        public string MoldName { get; set; }
        public Nullable<decimal> MoldQuantity { get; set; }
    }
}
