//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CommodityBom
    {
        public int CommodityBomID { get; set; }
        public int BomID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Remarks { get; set; }
        public bool IsDefault { get; set; }
        public bool InActive { get; set; }
        public string BomCode { get; set; }
        public string BomName { get; set; }
        public decimal BlockUnit { get; set; }
        public decimal BlockQuantity { get; set; }
    }
}
