//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinishedProduct()
        {
            this.FinishedProductDetails = new HashSet<FinishedProductDetail>();
        }
    
        public int FinishedProductID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public int FirmOrderID { get; set; }
        public int CustomerID { get; set; }
        public int CrucialWorkerID { get; set; }
        public int UserID { get; set; }
        public int PreparedPersonID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int LocationID { get; set; }
        public int ApproverID { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalQuantityFailure { get; set; }
        public decimal TotalSwarfs { get; set; }
        public decimal TotalQuantityReceipted { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public decimal TotalQuantityExcess { get; set; }
        public decimal TotalQuantityShortage { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FinishedProduct FinishedProducts1 { get; set; }
        public virtual FinishedProduct FinishedProduct1 { get; set; }
        public virtual FirmOrder FirmOrder { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedProductDetail> FinishedProductDetails { get; set; }
    }
}
