//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class FinishedHandoverViewDetail
    {
        public int FinishedHandoverDetailID { get; set; }
        public int FinishedHandoverID { get; set; }
        public int FinishedProductID { get; set; }
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public decimal Quantity { get; set; }
        public string Remarks { get; set; }
        public int FinishedProductPackageID { get; set; }
        public System.DateTime FinishedProductEntryDate { get; set; }
        public string SemifinishedProductReferences { get; set; }
        public string FirmOrderReference { get; set; }
        public string FirmOrderCode { get; set; }
        public System.DateTime FirmOrderEntryDate { get; set; }
    }
}
