//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class FinishedProductViewDetail
    {
        public int FinishedProductDetailID { get; set; }
        public int FirmOrderID { get; set; }
        public int FirmOrderDetailID { get; set; }
        public int PlannedOrderDetailID { get; set; }
        public int SemifinishedProductID { get; set; }
        public int SemifinishedProductDetailID { get; set; }
        public System.DateTime SemifinishedProductEntryDate { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public string Remarks { get; set; }
        public int WorkshiftID { get; set; }
        public System.DateTime WorkshiftEntryDate { get; set; }
        public string WorkshiftCode { get; set; }
        public string GoodsReceiptReference { get; set; }
        public string GoodsReceiptCode { get; set; }
        public System.DateTime BatchEntryDate { get; set; }
        public Nullable<decimal> QuantityRemains { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<int> SemifinishedHandoverID { get; set; }
        public int FinishedProductID { get; set; }
        public int PlannedOrderID { get; set; }
        public int PiecePerPack { get; set; }
        public decimal QuantityFailure { get; set; }
        public decimal Swarfs { get; set; }
        public string SemifinishedProductReference { get; set; }
        public decimal QuantityExcess { get; set; }
        public decimal QuantityShortage { get; set; }
    }
}
