//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class FinishedProductIndex
    {
        public int FinishedProductID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public string LocationCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public bool Approved { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalQuantityFailure { get; set; }
        public decimal TotalSwarfs { get; set; }
        public string FirmOrderReference { get; set; }
        public string FirmOrderCode { get; set; }
        public string FirmOrderSpecs { get; set; }
        public decimal TotalQuantityExcess { get; set; }
        public decimal TotalQuantityShortage { get; set; }
    }
}
