//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class GoodsReceiptPendingPlannedOrder
    {
        public int GoodsReceiptTypeID { get; set; }
        public int PlannedOrderID { get; set; }
        public string PlannedOrderCode { get; set; }
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime PlannedOrderEntryDate { get; set; }
        public string PlannedOrderReference { get; set; }
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string PlannedOrderCaption { get; set; }
    }
}
