//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class GoodsReceiptViewDetail
    {
        public int GoodsReceiptDetailID { get; set; }
        public int GoodsReceiptID { get; set; }
        public Nullable<int> PurchaseRequisitionID { get; set; }
        public Nullable<int> PurchaseRequisitionDetailID { get; set; }
        public string PurchaseRequisitionReference { get; set; }
        public string PurchaseRequisitionCode { get; set; }
        public Nullable<System.DateTime> PurchaseRequisitionEntryDate { get; set; }
        public Nullable<int> WarehouseTransferID { get; set; }
        public Nullable<int> WarehouseTransferDetailID { get; set; }
        public string WarehouseTransferReference { get; set; }
        public Nullable<System.DateTime> WarehouseTransferEntryDate { get; set; }
        public Nullable<int> WarehouseAdjustmentID { get; set; }
        public Nullable<int> WarehouseAdjustmentDetailID { get; set; }
        public string WarehouseAdjustmentReference { get; set; }
        public Nullable<System.DateTime> WarehouseAdjustmentEntryDate { get; set; }
        public Nullable<int> WarehouseAdjustmentTypeID { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<decimal> QuantityRemains { get; set; }
        public decimal Quantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MaterialIssueDetailID { get; set; }
        public Nullable<int> MaterialIssueID { get; set; }
        public Nullable<System.DateTime> MaterialIssueEntryDate { get; set; }
        public string WorkshiftName { get; set; }
        public Nullable<System.DateTime> WorkshiftEntryDate { get; set; }
        public string ProductionLinesCode { get; set; }
        public Nullable<int> FinishedProductPackageID { get; set; }
        public Nullable<int> FinishedProductID { get; set; }
        public Nullable<System.DateTime> FinishedProductEntryDate { get; set; }
        public string FirmOrderReference { get; set; }
        public string FirmOrderCode { get; set; }
        public string SemifinishedProductReferences { get; set; }
        public string FirmOrderSpecs { get; set; }
        public string GoodsReceiptReference { get; set; }
        public Nullable<System.DateTime> GoodsReceiptEntryDate { get; set; }
        public Nullable<System.DateTime> BatchEntryDate { get; set; }
    }
}
