//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class ReportIndex
    {
        public int ReportID { get; set; }
        public int ReportUniqueID { get; set; }
        public int ReportGroupID { get; set; }
        public string ReportGroupName { get; set; }
        public string ReportName { get; set; }
        public string ReportURL { get; set; }
        public int ReportTypeID { get; set; }
        public int SerialID { get; set; }
        public string Remarks { get; set; }
    }
}
