//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseTransferDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseTransferDetail()
        {
            this.GoodsReceiptDetails = new HashSet<GoodsReceiptDetail>();
        }
    
        public int WarehouseTransferDetailID { get; set; }
        public int WarehouseTransferID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int NMVNTaskID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> TransferOrderID { get; set; }
        public Nullable<int> TransferOrderDetailID { get; set; }
        public int WarehouseID { get; set; }
        public int WarehouseReceiptID { get; set; }
        public int GoodsReceiptID { get; set; }
        public int GoodsReceiptDetailID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public int BatchID { get; set; }
        public System.DateTime BatchEntryDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityReceipted { get; set; }
        public string Remarks { get; set; }
        public bool Approved { get; set; }
        public bool HasTransferOrder { get; set; }
        public int LocationReceiptID { get; set; }
        public int LocationIssuedID { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsReceiptDetail> GoodsReceiptDetails { get; set; }
        public virtual GoodsReceiptDetail GoodsReceiptDetail { get; set; }
        public virtual TransferOrderDetail TransferOrderDetail { get; set; }
        public virtual TransferOrder TransferOrder { get; set; }
        public virtual WarehouseTransfer WarehouseTransfer { get; set; }
    }
}
