//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class WorkshiftBase
    {
        public int WorkshiftID { get; set; }
        public string WorkshiftCode { get; set; }
        public string WorkshiftName { get; set; }
    }
}
